swagger: "2.0"
info:
  title: Cloud Endpoints + GCF
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: mimosa-esp-tfmdd2vwoq-uc.a.run.app
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/mimosa-256008"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "mimosa-256008"
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: helloGet
      x-google-backend:
        address: https://us-central1-mimosa-256008.cloudfunctions.net/hello
      responses:
        "200":
          description: A successful response
          schema:
            type: string
    post:
      consumes:
        - application/json
      produces:
        - application/json
        - text/xml
        - text/html
      operationId: helloPost
      x-google-backend:
        address: https://us-central1-mimosa-256008.cloudfunctions.net/hello
      responses:
        "200":
          description: A successful response
          schema:
            type: string
  /runtask:
    post:
      consumes:
        - application/json
      produces:
        - application/json
        - text/xml
        - text/html
      operationId: runtaskPost
      x-google-backend:
        address: https://us-central1-mimosa-256008.cloudfunctions.net/runtask
      responses:
        "200":
          description: A successful response
          schema:
            type: string
security:
  - firebase: []
