swagger: "2.0"
info:
  title: Cloud Endpoints + GCF
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: mimosa-esp-tfmdd2vwoq-uc.a.run.app
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/mimosa-256008"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "mimosa-256008"
paths:
  /api/v1/runtask:
    post:
      summary: "Run a task against a host"
      consumes:
        - application/json
      parameters:
        - in: body
          name: target
          description: The workspace and ID of the target host
          schema:
            $ref: "#/definitions/Target"
      operationId: api-v1-runtask
      x-google-backend:
        address: https://us-central1-mimosa-256008.cloudfunctions.net/api-v1-runtask
      responses:
        "200":
          description: A successful response
definitions:
  Target:
    type: object
    required:
      - workspace
      - id
    properties:
      workspace:
        type: string
      id:
        type: string
security:
  - firebase: []
