name: Build Mimosa
on: pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11
      id: go

    - name: Get dependencies
      run: |
        GO111MODULE=off go get github.com/golangci/golangci-lint/cmd/golangci-lint

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: make
